// Automatically generated by astro-icon
// a3f340e470212a1aa33d9cbf0485a6c903e56c4ba296c80d83cc580f203ec576

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "branches"
		| "fb"
		| "history"
		| "linkedin"
		| "privacy"
		| "secure_guard"
		| "twitter";
}